on:
  push:
    branches:
      - prod
  pull_request:
    branches:
      - prod
    
jobs:
  deploy:
    if: |
      (github.event_name == 'pull_request' && github.head_ref == 'python') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/prod')

    runs-on: [self-hosted,Linux,X64]

    environment: production

    env:
      ENVIRONMENTAL_VARIABLES: ${{ vars.ENVIRONMENTAL_VARIABLES }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install PM2
        run: sudo npm install -g pm2

      - name: Stop and Removing the PM2 Process
        run: pm2 stop guideco || true && pm2 delete guideco || true

      - name: Running deployment script
        run: bash .github/scripts/deploy.sh

      - name: Echo the Environment variables
        run: echo "$ENVIRONMENTAL_VARIABLES"
